<?php

function tbr_perdiem_views_api() {
   return array(
      'api' => 3,
   );
}

function tbr_perdiem_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form" && $form['#id'] == "views-exposed-form-per-diem-lookups-page") {

    $form['year']['#type'] = "select";
    $form['year']['#size'] = null;
    $form['year']['#options'] = array();
	$form['year']['#options'][''] = '-- Select --';

	$results = null;
	$cache_key = "perdiem_years";
	$cache = cache_get($cache_key);

	if ($cache) {
		//drupal_set_message("Content Type List Loaded from Cache: " . date("Y-m-d H:i:s", $cache->created));
		$results = $cache->data;
	}
	else {
	   //Set the database to the salaries database
	   db_set_active('tbr_data_salaries');

	   //Get distinct years
	   $result = db_query('SELECT DISTINCT FiscalYear FROM perdiem ORDER BY FiscalYear ASC');
       $results = $result->fetchAll();
	   cache_set($cache_key, $results, 'cache', CACHE_TEMPORARY);
	   //drupal_set_message("Content Type List Saved to Cache");

	   //Set the database back to the default drupal database
	   db_set_active();
   }

   foreach ($results as $record) {
	   //Add the years to the select list array
	   $form['year']['#options'][$record->FiscalYear] = $record->FiscalYear;
   }
  }
  }